spring:
  application:
    name: clan-tracker
  profiles:
    active:
      - dev
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    open-in-view: false
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            idleWaitTime: 7500
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  servlet:
    multipart:
      max-file-size: 32MB
springdoc:
  swagger-ui:
    use-root-path: true
wargaming:
  api-token:
server:
  port: 5002
cors:
  urls: http://localhost:5173/
  methods: GET, POST, DELETE