name: Release

on:
  workflow_dispatch:

jobs:
  shared-workflows:
    name: Shared Workflows
    uses: Th3-Hero/github-workflows-and-actions/.github/workflows/maven-release.yml@main
    with:
      java-version: '21'
      private-maven-proxy-repository: ${{ vars.PRIVATE_MAVEN_PROXY_REPOSITORY }}
      private-maven-user: ${{ vars.PRIVATE_MAVEN_USER }}
      private-npm-registry: ${{ vars.PRIVATE_NPM_REGISTRY }}
      private-server-base: ${{ vars.PRIVATE_SERVER_BASE }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      private-maven-token: ${{ secrets.PRIVATE_MAVEN_TOKEN }}
      private-npm-token: ${{ secrets.PRIVATE_NPM_TOKEN }}
